<div class="single_sidebar"> <img src="<?php echo $this->baseUrl('images/add1.png') ?>" alt="" /> 
</div>
<div class="single_sidebar">
    <div class="popular">
    <h2 class="title">Popular</h2>
    <ul>
        <li>
        <div class="single_popular">
            <p>Sept 24th 2045</p>
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit <a href="#" class="readmore">Read More</a></h3>
        </div>
        </li>
        <li>
        <div class="single_popular">
            <p>Sept 24th 2045</p>
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit <a href="#" class="readmore">Read More</a></h3>
        </div>
        </li>
        <li>
        <div class="single_popular">
            <p>Sept 24th 2045</p>
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit <a href="#" class="readmore">Read More</a></h3>
        </div>
        </li>
        <li>
        <div class="single_popular">
            <p>Sept 24th 2045</p>
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit <a href="#" class="readmore">Read More</a></h3>
        </div>
        </li>
        <li>
        <div class="single_popular">
            <p>Sept 24th 2045</p>
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit <a href="#" class="readmore">Read More</a></h3>
        </div>
        </li>
    </ul>
    <a class="popular_more">more</a> </div>
</div>
<div class="single_sidebar"> 
    <img src="<?php echo $this->baseUrl('images/add1.png') ?>" alt="" /> 
</div>
<div class="single_sidebar">
    <h2 class="title">ADD</h2>
    <img src="<?php echo $this->baseUrl('images/add2.png') ?>" alt="" /> 
</div>
