<?php 
$listPostsDev = $this->layout()->listPostDev;
$listPostsEdu = $this->layout()->listPostsEdu;
$listPostsTech = $this->layout()->listPostsTech;
$listPostsTip = $this->layout()->listPostsTip;
?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<ul id="nav">
      <li><a href="#" ><b>LẬP TRÌNH</b></a>
        <ul>
          <?php foreach ($listPostsDev as $listPost) : ?>
            <li id="<?php echo $listPost['id'] ?>"><a ><?php echo $listPost['list_post_title'] ?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
      <li><a href="#"><b>GIÁO DỤC</b></a>
        <ul>
          <?php foreach ($listPostsEdu as $listPost) : ?>
          <li id="<?php echo $listPost['id'] ?>"><a ><?php echo $listPost['list_post_title'] ?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
      <li><a href="#"><b>CÔNG NGHỆ</b></a>
        <ul>
          <?php foreach ($listPostsTech as $listPost) : ?>
          <li id="<?php echo $listPost['id'] ?>"><a ><?php echo $listPost['list_post_title'] ?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
      <li><a href="#"><b>HƯỚNG DẪN</b></a>
        <ul>
          <?php foreach ($listPostsTip as $listPost) : ?>
          <li id="<?php echo $listPost['id'] ?>"><a ><?php echo $listPost['list_post_title'] ?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
      <li><a href="#"><b>TÀI LIỆU</b></a></li>
      <li><a href="#"><b>CHÚNG TÔI LÀ AI</b></a></li>
</ul>