<input type="button" name="show" id="show" value="show">
<input type="button" name="Login" value="Login" id="Login">
<input type="button" name="Logout" value="Logout" id="Logout">
<div id="dialog" title="Basic dialog 1111"  style=" color:red; backround-color:blue">
	<font id="close">X</font>
  <p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
</div>