<?php 
$listBestView = $this->listBestView;
$listNewest = $this->listNewest;
?>
<div class="main_content floatleft">
    <div class="left_coloum floatleft">
        <div class="single_left_coloum_wrapper">
            <h2 class="title">BÀI VIẾT ĐƯỢC QUAN TÂM NHẤT</h2>
            <a class="more" href="#">more</a>
            <?php foreach ($listBestView as $bestView) : ?>
            <div class="single_left_coloum floatleft"> <img src="images/single_featured.png" alt="" />
                <h3><?php echo $bestView['post_title'] ?></h3>
                <p><?php echo $bestView['post_description'] ?>...</p>
                <a class="readmore" href="#">read more</a> 
            </div>
            <?php endforeach; ?>
        </div>
        <div class="single_left_coloum_wrapper">
            <h2 class="title">BÀI VIẾT MỚI NHẤT</h2>
            <a class="more" href="#">more</a>
            <?php foreach ($listNewest as $newest) : ?>
            <div class="single_left_coloum floatleft"> <img src="<?php $this->baseUrl(APPLICATION_PATH.'images/single_featured.png'); ?>" alt="" />
                <h3><?php echo $newest['post_title'] ?></h3>
                <p><?php echo $newest['post_description'] ?></p>
                <a class="readmore" href="#">read more</a> 
            </div>
            <?php endforeach; ?>
        </div>
        <div class="single_left_coloum_wrapper gallery">
            <h2 class="title">DANH SÁCH BÀI HỌC</h2>
            <a class="more" href="#">more</a> <img src="images/single_featured.png" alt="" /> 
            <img src="images/single_featured.png" alt="" /> 
            <img src="images/single_featured.png" alt="" /> 
            <img src="images/single_featured.png" alt="" /> 
            <img src="images/single_featured.png" alt="" /> 
            <img src="images/single_featured.png" alt="" /> 
        </div>
        <div class="single_left_coloum_wrapper single_cat_left">
            <h2 class="title">TIN CÔNG NGHỆ MỚI NHẤT</h2>
            <a class="more" href="#">more</a>
        <div class="single_cat_left_content floatleft">
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit </h3>
            <p>Nulla quis lorem neque, mattis venenatis lectus. In interdum ullamcorper dolor ...interdum</p>
            <p class="single_cat_left_content_meta">by <span>John Doe</span> |  29 comments</p>
        </div>
        <div class="single_cat_left_content floatleft">
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit </h3>
            <p>Nulla quis lorem neque, mattis venenatis lectus. In interdum ullamcorper dolor ...interdum</p>
            <p class="single_cat_left_content_meta">by <span>John Doe</span> |  29 comments</p>
        </div>
        <div class="single_cat_left_content floatleft">
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit </h3>
            <p>Nulla quis lorem neque, mattis venenatis lectus. In interdum ullamcorper dolor ...interdum</p>
            <p class="single_cat_left_content_meta">by <span>John Doe</span> |  29 comments</p>
        </div>
        <div class="single_cat_left_content floatleft">
            <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit </h3>
            <p>Nulla quis lorem neque, mattis venenatis lectus. In interdum ullamcorper dolor ...interdum</p>
            <p class="single_cat_left_content_meta">by <span>John Doe</span> |  29 comments</p>
        </div>
        </div>
    </div>
    <div class="right_coloum floatright">
        <div class="single_right_coloum">
        <h2 class="title">LẬP TRÌNH</h2>
        <ul>
            <li>
            <div class="single_cat_right_content">
                <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit</h3>
                <p>Nulla quis lorem neque, mattis venen atis lectus. In interdum ull amcorper dolor eu mattis.</p>
                <p class="single_cat_right_content_meta"><a href="#"><span>read more</span></a> 3 hours ago</p>
            </div>
            </li>
            <li>
            <div class="single_cat_right_content">
                <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit</h3>
                <p>Nulla quis lorem neque, mattis venen atis lectus. In interdum ull amcorper dolor eu mattis.</p>
                <p class="single_cat_right_content_meta"><a href="#"><span>read more</span></a> 3 hours ago</p>
            </div>
            </li>
            <li>
            <div class="single_cat_right_content">
                <h3>Lorem ipsum dolor sit amet conse ctetur adipiscing elit</h3>
                <p>Nulla quis lorem neque, mattis venen atis lectus. In interdum ull amcorper dolor eu mattis.</p>
                <p class="single_cat_right_content_meta"><a href="#"><span>read more</span></a> 3 hours ago</p>
            </div>
            </li>
        </ul>
        <a class="popular_more" href="#">more</a> </div>
        <div class="single_right_coloum">
        <h2 class="title">GIÁO DỤC</h2>
        <div class="single_cat_right_content editorial"> <img src="images/editorial_img.png" alt="" />
            <h3>Lorem ipsum dolor sit amet con se cte tur adipiscing elit</h3>
        </div>
        <div class="single_cat_right_content editorial"> <img src="images/editorial_img.png" alt="" />
            <h3>Lorem ipsum dolor sit amet con se cte tur adipiscing elit</h3>
        </div>
        <div class="single_cat_right_content editorial"> <img src="images/editorial_img.png" alt="" />
            <h3>Lorem ipsum dolor sit amet con se cte tur adipiscing elit</h3>
        </div>
        <div class="single_cat_right_content editorial"> <img src="images/editorial_img.png" alt="" />
            <h3>Lorem ipsum dolor sit amet con se cte tur adipiscing elit</h3>
        </div>
        </div>
    </div>
</div>
